USE [master]
GO

/****** Object:  Database [BookingApp]    Script Date: 21-Feb-25 1:05:44 PM ******/
CREATE DATABASE [BookingApp]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BookingApp', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\BookingApp.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BookingApp_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\BookingApp_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BookingApp].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BookingApp] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BookingApp] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BookingApp] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BookingApp] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BookingApp] SET ARITHABORT OFF 
GO

ALTER DATABASE [BookingApp] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BookingApp] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BookingApp] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BookingApp] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BookingApp] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BookingApp] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BookingApp] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BookingApp] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BookingApp] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BookingApp] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BookingApp] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BookingApp] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BookingApp] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BookingApp] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BookingApp] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BookingApp] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BookingApp] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BookingApp] SET RECOVERY FULL 
GO

ALTER DATABASE [BookingApp] SET  MULTI_USER 
GO

ALTER DATABASE [BookingApp] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BookingApp] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BookingApp] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BookingApp] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BookingApp] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BookingApp] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BookingApp] SET QUERY_STORE = ON
GO

ALTER DATABASE [BookingApp] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [BookingApp] SET  READ_WRITE 
GO

